# Generated by Django 4.0.2 on 2022-02-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='decription',
            new_name='description',
        ),
    ]
