# Generated by Django 4.0.2 on 2022-02-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_cat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='user',
        ),
    ]
